---
- hosts: all

  tasks:

  - name: Add repo with nvidia drivers
    apt_repository:
      repo: ppa:graphics-drivers
      state: present

  - name: Update APT packages info
    apt:
      update_cache: yes

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - gitk
      - vim
      - python3-pip
      - nvidia-driver-430
      - keepassx
      - rdesktop
      - network-manager-l2tp-gnome # for tutti VPN
      - python3-venv

  - name: Make vim the default editor
    become: no
    lineinfile:
      create: yes
      path: ~/.selected_editor
      regexp: 'SELECTED'
      line: SELECTED_EDITOR="/usr/bin/vim.basic"

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Set global git username
    become: no
    git_config:
      name: user.name
      scope: global
      value: "{{ git_user_name }}"

  - name: Set global git email
    become: no
    git_config:
      name: user.email
      scope: global
      value: "{{ git_user_email }}"

  - name: Set git editor
    become: no
    git_config:
      name: core.editor
      scope: global
      value: vim

  - name: Download bashrc
    become: no
    get_url:
      url: https://raw.githubusercontent.com/Dmitrii-I/configs/master/bashrc
      dest: ~/.bashrc
      mode: 0600
      force: yes

  - name: Download bash_profile
    become: no
    get_url:
      url: https://raw.githubusercontent.com/Dmitrii-I/configs/master/bashrc
      dest: ~/.bash_profile
      mode: 0600
      force: yes

  - name: Download psqlrc
    become: no
    get_url:
      url: https://raw.githubusercontent.com/Dmitrii-I/configs/master/psqlrc
      dest: ~/.psqlrc
      mode: 0600
      force: yes

  - name: Download sqliterc
    become: no
    get_url:
      url: https://raw.githubusercontent.com/Dmitrii-I/configs/master/sqliterc
      dest: ~/.sqliterc
      mode: 0600
      force: yes

  - name: Create ~/.vim/autoload directory
    tags:
      - vim
    become: no
    file:
      path: ~/.vim/autoload
      state: directory
      mode: 0755

  - name: Create ~/.vim/bundle directory
    tags:
      - vim
    become: no
    file:
      path: ~/.vim/bundle
      state: directory
      mode: 0755

  - name: Create ~/.vim/undo directory
    tags:
      - vim
    become: no
    file:
      path: ~/.vim/undo
      state: directory
      mode: 0755

  - name: Download pathogen.vim
    tags:
      - vim
    become: no
    get_url:
      url: https://tpo.pe/pathogen.vim
      dest: ~/.vim/autoload/pathogen.vim
      mode: 0644
      force: yes

  - name: Install vim-colors-solarized
    tags:
      - vim
    become: no
    git:
      repo: 'https://github.com/altercation/vim-colors-solarized.git'
      dest: ~/.vim/bundle/vim-colors-solarized
      clone: yes
      force: yes
      update: no

  - name: Install vim-airline
    tags:
      - vim
    become: no
    git:
      repo: 'https://github.com/vim-airline/vim-airline.git'
      dest: ~/.vim/bundle/vim-airline
      clone: yes
      force: yes
      update: no

  - name: Install Pycharm from snap
    shell: snap install pycharm-community --classic

  - name: Install VSCode
    shell: snap install code --classic


  - name: Create a directory for Gnome shells
    become: no
    file:
      path: ~/.local/share/gnome-shell/extensions
      state: directory
      mode: 0755

  - name: Install `Put Window` GNOME shell extension
    become: no
    git:
      repo: 'https://github.com/negesti/gnome-shell-extensions-negesti.git'
      dest: ~/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org
      clone: yes
      force: yes
      update: no
      version: v26

  - name: Install Slack
    apt:
      deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.0.1-amd64.deb

  - name: Install dbeaver
    apt:
      deb: https://github.com/dbeaver/dbeaver/releases/download/6.1.3/dbeaver-ce_6.1.3_amd64.deb

  - name: Fix audio 1 or 3
    become: yes
    lineinfile:
      path: /etc/modprobe.d/alsa-base.conf
      regexp: 'options.*snd-hda-intel.*single_cmd=1'
      line: options snd-hda-intel single_cmd=1

  - name: Fix audio 2 or 3
    become: yes
    lineinfile:
      path: /etc/modprobe.d/alsa-base.conf
      regexp: 'options.*snd-hda-intel.*probe_mask=1'
      line: options snd-hda-intel probe_mask=1

  - name: Fix audio 3 or 3
    become: yes
    lineinfile:
      path: /etc/modprobe.d/alsa-base.conf
      regexp: 'options.*snd-hda-intel.*model=basic'
      line: options snd-hda-intel model=basic

  - name : Download and unarchive Terraform 0.12.4
    become: no
    tags:
      - terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.4/terraform_0.12.4_linux_amd64.zip
      dest: ~/.local/bin/
      remote_src: yes

  - name: Install RStudio
    apt:
      deb: https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.1335-amd64.deb

  - name: Install fzf binary
    become: yes
    unarchive:
      src: https://github.com/junegunn/fzf-bin/releases/download/0.18.0/fzf-0.18.0-linux_amd64.tgz
      dest: /usr/local/bin
      remote_src: yes

